# Generated by Django 6.0.7 on 2026-08-07 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('work_done', models.TextField()),
                ('progress_percentage', models.PositiveIntegerField()),
                ('workers_present', models.PositiveIntegerField()),
                ('weather', models.CharField(choices=[('SUNNY', 'Sunny'), ('CLOUDY', 'Cloudy'), ('RAINY', 'Rainy')], default='SUNNY', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='tasks.task')),
            ],
        ),
    ]
