# Generated by Django 6.0.7 on 2026-09-29 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='remarks',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='days_present',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payroll',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('HOLD', 'On Hold')], default='PENDING', max_length=20),
        ),
    ]
